### ISSUE TITLE
metadata redo

### ISSUE THREAD

**Issue by mbaudis** [ga4gh/metadata-team#10]
Please use this space to comment on the new metadata specs. We need some discussion before getting this out as a PR against the main branch in "schemas".

[metadata_redo.avdl](https://github.com/ga4gh/metadata-team/blob/master/avro-playground/metadata_redo.avdl)

**Comment by diekhans** [comment]
Hi Michael,

Nicole visit UCSC last week and we did a pass over your doc.
Sorry I haven't gotten to give you feed back yet.

Mark

**Comment by mbaudis** [comment]
This is a copy of the comments about editing the  @eleanorstanley edit from 2015-02-25.

<pre>
[EAGLE: OntologyTerm.dateTimeObserved - is this useful in the OntologyTerm record? Should this be an Observation attribute?]
[EAGLE: OntologyTerm.ageObserved - is this useful in the OntologyTerm record? Should this be an Observation attribute?]
</pre>

* if you describe e.g. a diagnosis using an ontology, a time point is needed and age (either direct or calculated) highly relevant
* observations clearly need dateTime, too, but this doesn't help (or only indirect)

<pre>
[EAGLE: presuming use of individual was chosen over 'Subject' as this schema is to cover all species, not just human?]
</pre>

* yes; there were discussions

<pre>
[EAGLE: add what version of the software was used?]
</pre>                                                                                                    

* we don't want to overdo the structure here; version would be assumed to be part of the software description

**Missing attributes**

I've removed the following note about missing attributes. This is a larger discussion, and we are collecting input e.g. here: https://docs.google.com/spreadsheets/d/1L_i2lzhG244afBRwaJ_Ue5GQ_1jMiN-9i3qHqKCPE8w/edit#gid=0

<pre>
[EAGLE: Suggestion of missing records to capture clinical data that seem to be absent from existing schema:
Clinical study: Capture the date, time, place and name of physician where patient visited/registered to
Investigator name
Investigator identifier
Study site
Study country
TimeDate consent
TimeDate end of participation

Clinical event/adverse event: Capture the adverse event(s) that prompted the clinical study/visit
Term
affected body system 
Severity
TimeDate of Occurrence

This could be further extended to include records/fields for:
CRF
Medical history/hospital record
Physical examination data
I have not expanded these further ... ]
</pre>
